version: "2"
services:
    node_web:
      container_name: app
      image: floody
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - db
    db:
      image: aashreys/mongo-auth:latest
      container_name: db
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=komobile
        - MONGODB_ADMIN_PASS=KoMobile2019!*
        - MONGODB_APPLICATION_DATABASE=komobile
        - MONGODB_APPLICATION_USER=komobile
        - MONGODB_APPLICATION_PASS=KoMobile2019!*
      volumes:
        - ./data/db:/data/db
      ports:
        - "27017:27017"

