version: "2"
services:
    node_web:
      container_name: app
      build: .
      restart: always
      environment:
        - "DB_URL=$DB_URL"
        - "RESOURCES_PATH=$RESOURCES_PATH"
        - "BASE_URL=$BASE_URL"
        - "UPLOAD_FILE_BASE_URL=$UPLOAD_FILE_BASE_URL"
        - "FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL"
        - "REGISTRATION_TOKEN=$REGISTRATION_TOKEN"
        - "PORT=$PORT"
      ports:
        - "8080:8080"
        - "80:8080"
      depends_on:
        - db
    db:
      image: aashreys/mongo-auth:latest
      container_name: db
      environment:
        - AUTH=yes
        - MONGODB_ADMIN_USER=komobile
        - MONGODB_ADMIN_PASS=KoMobile2019!*
        - MONGODB_APPLICATION_DATABASE=komobile
        - MONGODB_APPLICATION_USER=komobile
        - MONGODB_APPLICATION_PASS=KoMobile2019!*
      volumes:
        - ./data/db:/data/db
      ports:
        - "27018:27017"

